## TASK 01= DATA CLEANING

### VIEWING SALES DOCUMENT SALES 2017

In [3]:
import pandas as pd

In [10]:
sales_data_2017=pd.read_csv("sales_data_2017.csv")
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

### VIEWING SALES DOCUMENT SALES 2018

In [11]:
sales_data_2018=pd.read_csv("sales_data_2018.csv")
sales_data_2018

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

### VIEWING SALES DOCUMENT SALES 2019

In [12]:
sales_data_2019=pd.read_csv("sales_data_2019.csv")
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### MERGERING 3 DOCUMENT INTO SINGLE FILE USING CONCAT

In [8]:
combine_sales_data=pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])
combine_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### VIEWING DATATYPES OF EACH COLUMNS

In [14]:
combine_sales_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

### CHANGING DATE --- DATATYPE OBJECT INTO DATATIME FORMAT:

In [23]:
combine_sales_data["Date"] = pd.to_datetime(combine_sales_data["Date"],dayfirst=True,errors="coerce")

In [24]:
combine_sales_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                       object
Rate                      object
Gross                     object
Disc                      object
Voucher Amount            object
dtype: object

### ROWS AND COLUMS OBSERVATION

In [28]:
combine_sales_data.shape

(111206, 9)

### check null values is there ( true / false):

In [29]:
combine_sales_data.isnull()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...
19171,False,False,False,False,False,False,False,True,True
19172,True,True,True,True,True,True,True,True,True
19173,True,True,True,True,True,True,True,True,True
19174,True,False,True,True,False,False,False,False,False
19175,True,False,True,True,False,False,False,False,False

### check null values is there ( true / false) using sum function:

In [30]:
combine_sales_data.isnull().sum()

Date               15644
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

### REMOVE DUPLICATE ROWS:

In [32]:
combine_sales_data.drop_duplicates(inplace=True)
combine_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaT,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaT,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [33]:
combine_sales_data.shape

(96624, 9)

## task 2

### MERGERING -------------------

In [3]:
import pandas as pd

file_1 = pd.read_csv("sales_data_2017.csv")

file_2 = pd.read_csv("data.txt",sep="\t")

merged = pd.merge(file_1, file_2, on="Product")

print(merged)

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty_x, Rate, Gross, Disc, Voucher Amount, order_id, Qty_y, choice_description, item_price]
Index: []

## TASK 3

### EXPLORE LIST COMPREHENSION USING LAMBDA

In [7]:
female_smoker_list= pd.read_csv("insurance.csv")

female_smoker_list= female_smoker_list.apply(lambda row: row["sex"] == "female" and row["smoker"] == "yes",axis=1).sum()

print("Female smokers:", female_smoker_list)

Female smokers: 115

## TASK 4

### LAMDA FUNCTIONS WITH MAP , FILTER ,REDUCE:

#### 01.MAP 
* LAMBDA - CREATE FUNCTION, DOES NOT PROCESS DATA
* MAP -    USE FUNCTION, PROCESS THE DATA

In [11]:
import pandas as pd
map_file = pd.read_csv("insurance.csv")

female_smoker_list = (map_file["sex"].map(lambda x: x == "female") & map_file["smoker"].map(lambda x: x == "yes"))

print("Female smokers:", female_smoker_list)

Female smokers: 0        True
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337     True
Length: 1338, dtype: bool

In [12]:
map_file.shape

(1338, 7)

#### 02.FILTER
* FILTER - ONLY GIVE ANSWER THE CONDITION MATCHES
* ZIP - USED FOR COMBINE BOTH TABLES

In [19]:
import pandas as pd
filter_FILE = pd.read_csv("insurance.csv")

female_smokers = list(filter( lambda row: row[0] == "female" and row[1] == "yes",zip(filter_FILE["sex"], filter_FILE["smoker"])))

print("Female smokers:",female_smokers)

Female smokers: [('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes'), ('female', 'yes')]

#### 03.REDUCE

* REDUCE - ITS ONLY GIVE TOTAL

In [4]:
import pandas as pd
from functools import reduce

insurance_file = pd.read_csv("insurance.csv")
max_bmi = reduce(lambda x, y: x if x > y else y, insurance_file["bmi"])

print("Maximum BMI:", max_bmi)

Maximum BMI: 53.13